### PR TITLE
Wip mix fix 9

### PR DESCRIPTION
**Pull request by cunei**
Fixes for issues 163 and 160; will release 0.9.3-M3

### CODE REVIEW

**Comment by adriaanm** [comment]
Thanks, it would also be useful to have the more detailed error message when relativization fails: https://github.com/typesafehub/dbuild/pull/165/files#diff-422b3af6b76b7cb0421b2202c31496e3R166

**Comment by cunei** [comment]
It would not hurt, but it is unlikely to be necessary: the error condition should not occur at all during normal usage, and the additional diagnostic would be useless for the end user. In particular, the relativization occurs simply between a base dir and files that are obtained traversing the same dir (see https://github.com/typesafehub/dbuild/blob/12771c5987a50a48d2e985abc2fbea2a481e7d56/deploy/src/main/scala/com/typesafe/dbuild/deploy/Deploy.scala#L130), so a recurrence of #160 is quite unlikely.

**Comment by adriaanm** [comment]
It happened to me. I felt it would've helped me diagnose what was going on.

**Comment by jsuereth** [comment]
LGTM

**Pull request merged**
